### ISSUE TITLE
Proxy not set up using Ethers

### ISSUE THREAD

**Issue by NBMSacha** [ayanamitech/web3-providers-axios#1]
Hello! 

I followed the documentation, and built this little piece of code:

```
import { ethers } from 'ethers';
import { Web3AxiosProvider } from 'web3-providers-axios';
import createHttpsProxyAgent from 'https-proxy-agent';
const provider = new ethers.providers.Web3Provider(new Web3AxiosProvider('https://polygon-rpc.com', {
    agent: {
        https: createHttpsProxyAgent(
            'http://xx-xx@p.webshare.io:80',
        )
    }
}));

const responses: any[] = [];

for (let i = 30032204 - (500 * 10000); i < 30022204; i += 10000) {
    responses.push(provider.getLogs({
        fromBlock: i,
        toBlock: i + 10000,
        address: '0xdCF5b52f2E64C49F2E51B8D39899e4d2D63f3640',
        topic: '0xc83ad1914dc2114ca21cdee11903ccc28a2ce572f5aefc267087c39796fb3692'
    } as any));
}

Promise.all(responses).then(r => {
    console.log(r.length)
})
```

However, the proxy isn't used at all and all the queries are sent directly to the RPC : 
![image](https://user-images.githubusercontent.com/89188530/175833170-6db6e212-c6fb-4f3d-ab19-1a8505c43a1b.png)
<img width="487" alt="image" src="https://user-images.githubusercontent.com/89188530/175833185-8bbf8ada-d083-445b-8863-a49b857a4de1.png">

Any hint on what could be the issue on my side/the lib side? Thanks!

**Comment by ayanamidev** [comment]
@NBMSacha Hello, could you edit your script like the following?


```
import { HttpsProxyAgent } from 'https-proxy-agent';

const provider = new ethers.providers.Web3Provider(new Web3AxiosProvider('https://polygon-rpc.com', {
    agent: {
        https: new HttpsProxyAgent(
            'http://kwxrvcvx-rotate:m5fyjx2wpqi6@p.webshare.io:80',
        )
    }
}));
```

Somehow related with https://github.com/TooTallNate/node-https-proxy-agent/issues/123#issuecomment-890028901

**Comment by NBMSacha** [comment]
Hey! 
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/89188530/175957850-d3770493-1a02-47d4-9c16-19ffc389e426.png">
Unfortunately, it's still not working as expected :( 

By the way, could you edit your message like I did on the first message of the issue, because I think the informations in the URL may be sensitive. Thanks! 😅

**Comment by ayanamidev** [comment]
@NBMSacha That is weird, when I tried with socks5 proxy agent, it worked without concealing the IP. Will definitely look into this issue.

**Comment by NBMSacha** [comment]
I may have this issue on the proxy rotator side - I'm investing how wireshark is displaying the IP so I can make sure the proxy is down. What's the difference between socks5 and https proxy agents? Can I use that to replace it? My Telegram to chat more easily : t.me/NBMSacha

Ps: I can tip you a little something if we get this working even tho you probably don't make this for money!!

**Comment by NBMSacha** [comment]
Ok, just tested with non-rotator proxies, and tested on axios. 

- On rotator proxies with axios : no IP change on wireshark
- Without rotator proxies with axios : proxy IP on wireshark
- Without rotator with the library : no IP change on wireshark, RPC IP.

So I guess there is something going wrong. May be due to password/username?

**Comment by ayanamidev** [comment]
After spinning up the standalone squid http proxy, I have confirmed it is working well ( and also rechecked the codebase again as well ), if any problem exists with the proxy connection, it could be a problem with the proxy agent or the server.
